//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImagineCup2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programme
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> stationId { get; set; }
        public string moto { get; set; }
    
        public virtual station station { get; set; }
    }
}
