//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImagineCup2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempUser
    {
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public Nullable<bool> accountCreated { get; set; }
        public Nullable<int> stationID { get; set; }
    
        public virtual station station { get; set; }
    }
}
